language: node_js

node_js:
  - '7'

cache:
  directories:
    # Cache project modules
    - node_modules
    # Cache global installed modules
    - $(npm config get prefix)/bin/github-changes

env:
  global:
    - CXX=g++-4.8
    - UAT_ENDPOINT=http://gfg.pricing-engine.uat.s3-website-ap-southeast-1.amazonaws.com
    - UAT_S3_URI=s3://gfg.pricing-engine.uat
    - PROD_ENDPOINT=http://gfg.pricing-engine.prod.s3-website-ap-southeast-1.amazonaws.com
    - PROD_S3_URI=s3://gfg.pricing-engine.prod

sudo:
 required

services:
  - docker

# This is needed to avoid building all the tags pushed by travis
branches:
  except:
    - /^v?\d+\.\d+\.\d+$/
    - master

branches:
  only:
    - develop


#TODO caching of node_modules
before_install:
  - npm install
  - npm prune

script:
  - npm run test

before_deploy:
  # Install any dependencies required for building your site here.
  # `awscli` is required for invalidation of CloudFront distributions and sync file to s# bucket
  - pip install --user awscli
  - npm install -g github-changes
  - docker run -d -p 4444:4444 -v /dev/shm:/dev/shm selenium/standalone-chrome:3.0.1-germanium

deploy:
  - provider: script
    script:
      # Launch CI/CD pipeline scripts
      - ./ops/cicd_scripts/cicd.sh
    skip_cleanup: true
    on:
      branch: develop

addons:
 apt:
   sources:
     - ubuntu-toolchain-r-test
   packages:
     - g++-4.8
